/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public static void main(String[] args) {
        LogParsing.executeLogParsing();

        System.out.println(LongestSubstring.lengthOfLongestSubstring("pwwwkewa"));

        int[] coins = { 25, 10, 5 };
        int target = 30;
        System.out.println("Minimum coins needed: " + Coin.minCoins(coins, target));
    }
}
